name: Update Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build backend
        run: cd api && docker build -t shiro1331/devops-qr-code-backend .
      - name: build frontend
        run: cd front-end-nextjs && docker build -t shiro1331/devops-qr-code-frontend .
