name: Update Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: check path
        run: ls -la
      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-qr-code-backend ./api
      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-qr-code-frontend ./front-end-nextjs
