name: Update Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build backend
        run: docker build -t ${{ secrets.DOCKERHUB_TOKEN }}/devops-qr-code-backend ./api
      - name: build frontend
        run: docker build -t ${{ secrets.DOCKERHUB_TOKEN }}/devops-qr-code-frontend ./front-end-nextjs
